sudo: required
language: php
dist: trusty

php:
  - 7.0
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE dusk_demo;'

install:
  - travis_retry composer install --no-interaction
  - sudo apt-get install php7.1
  - sudo apt-get install network-manager libnss3-tools jq xsel
  - composer global require cpriego/valet-linux
  - ~/.config/composer/vendor/bin/valet install

before_script:

script:
