sudo: required
language: php
dist: trusty

php:
  - 7.0
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE dusk_demo;'

install:
  - travis_retry composer install --no-interaction

before_script:
  - sudo apt-get install nginx

script:
